[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "CsQYgrrqQoSwBUQF8ro7aFJgzyhjpUymbiMBeRFiv4Db"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xalexus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
